[versions]
boot-gradle = "2.4.3"
management-gradle = "1.0.11.RELEASE"

groovy = "4.0.11"
jgiven = "0.15.3"

[libraries]
gradleplugin-boot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "boot-gradle" }
gradleplugin-management = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "management-gradle" }

gradleplugin-release = { module = "net.researchgate:gradle-release", version = "2.8.1" }
gradleplugin-sonarqube = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version = "4.0.0.2929" }

groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
boot-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "boot-gradle" }
boot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "boot-gradle" }
boot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "boot-gradle" }

jgiven-junit = { module = "com.tngtech.jgiven:jgiven-junit", version.ref = "jgiven" }
jgiven-spring = { module = "com.tngtech.jgiven:jgiven-spring", version.ref = "jgiven" }