micronaut:
  application:
    name: Sample JWeb Console
#  router:
#    static-resources:
#      jweb-console:
#        enabled: true
#        mapping: "/**"
#        paths: "classpath:public"
netty:
  default:
    allocator:
      max-order: 3
jweb:
  console:
    enabled: true